apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: {{ .Release.Namespace }}
data:
  SPRING_PROFILES_ACTIVE: "dev"
  EUREKA_CLIENT_REGION: "default"
  EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT: "myzone"
  EUREKA_CLIENT_SERVICEURL_MYZONE: "http://service-discovery:8761/eureka"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-discovery:8761/eureka/"
